sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t fabriciocozer/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true fabriciocozer/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-apps"
  env: "Dockerapps-env"
  bucket_name: "elasticbeanstalk-us-east-1-781468328399"
  bucket_path: "docker-apps"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
